# Generated by Django 4.0.6 on 2022-08-06 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0002_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('workplace', models.CharField(blank=True, max_length=20, null=True)),
                ('total_coins', models.IntegerField(default=5)),
                ('books_recieved', models.IntegerField(default=0)),
                ('books_shared', models.IntegerField(default=0)),
                ('birthday', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
