# Generated by Django 4.0.6 on 2022-08-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile_about_profile_facebook_profile_insta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
