# Generated by Django 4.0.6 on 2022-08-06 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0006_alter_profile_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile_image',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('img', models.ImageField(upload_to='documents/')),
            ],
        ),
    ]
