# Generated by Django 4.0.6 on 2022-08-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_image',
            name='img',
            field=models.ImageField(null=True, upload_to='documents/'),
        ),
    ]
