# Generated by Django 4.0.6 on 2022-08-19 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_alter_profile_image_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('pubdate', models.CharField(max_length=50)),
                ('img', models.ImageField(null=True, upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='book_instances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=50)),
                ('img', models.ImageField(null=True, upload_to='documents/')),
                ('edition', models.CharField(max_length=20)),
                ('age', models.IntegerField(null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('price', models.IntegerField(null=True)),
                ('is_pending', models.BooleanField(default=True)),
                ('is_recieved', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.book')),
                ('requested', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('requesters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requesters_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
