# Generated by Django 4.0.6 on 2022-08-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_book_review_book_instances'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_instances',
            old_name='requesters',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='book_instances',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book_instances',
            name='details',
            field=models.CharField(max_length=101, null=True),
        ),
        migrations.AddField(
            model_name='book_instances',
            name='hard_cover',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='book_instances',
            name='paper_back',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='book_instances',
            name='pubdate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book_instances',
            name='publisher',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
