# Generated by Django 4.0.6 on 2022-08-19 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_book_author_alter_book_name_alter_book_pubdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='img',
        ),
    ]
