# Generated by Django 4.0.6 on 2022-08-23 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0016_alter_book_instances_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_instances',
            name='requested',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
