# Generated by Django 4.0.6 on 2022-08-26 14:35

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0017_alter_book_instances_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_instances',
            name='not_interested',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book_instances',
            name='post_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='book_instances',
            name='requested',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
