# Generated by Django 4.0.6 on 2022-08-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_book_instances_not_interested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_instances',
            name='not_interested',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
