# Generated by Django 4.0.6 on 2022-08-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_book_instances_not_interested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_instances',
            name='recieved_date',
            field=models.DateField(null=True),
        ),
    ]
