# Generated by Django 4.0.6 on 2022-08-26 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_profile_location_alter_profile_profession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_instances',
            name='requested',
        ),
    ]
