# Generated by Django 4.0.6 on 2022-08-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_req_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_instances',
            name='requested',
            field=models.ManyToManyField(to='main.req_user'),
        ),
    ]
