# Generated by Django 4.0.6 on 2022-08-26 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0026_remove_book_instances_requested_req_user_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req_user',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
