# Generated by Django 4.0.6 on 2022-08-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_book_author_alter_book_isbn_alter_book_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify',
            field=models.BooleanField(default=False),
        ),
    ]
