# Generated by Django 4.0.6 on 2022-08-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_profile_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_coins',
            field=models.IntegerField(default=500),
        ),
    ]
